# Generated by Django 3.0.2 on 2020-02-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200203_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
