# Generated by Django 3.0.2 on 2020-02-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_upload_upload_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='upload_at',
        ),
    ]
