# Generated by Django 3.0.2 on 2020-02-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_upload_upload_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
