# Generated by Django 3.0.2 on 2020-01-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='document',
        ),
    ]
