# Generated by Django 3.0.2 on 2020-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
