# Generated by Django 3.0.2 on 2020-02-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='document',
        ),
    ]
